title: ğŸ…°ğŸ…½ğŸ…³ğŸ†ğŸ…¾ğŸ…¸ğŸ…³  ğŸ…³ğŸ…´ğŸ…¿ğŸ…´ğŸ…½ğŸ…³ğŸ…´ğŸ…½ğŸ…²ğŸ†ˆ  ğŸ…»ğŸ…¸ğŸ†‚ğŸ†ƒ
description: List of all (almost) important dependencies and their resources for android development (Java and Kotlin). In this repository, if you didn't find any important dependencies or resources feel free to contribute here.
show_downloads: true
google_analytics: true
theme: jekyll-theme-cayman
